server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  queue:
    queue_type: nsqd
    addr: 127.0.0.1:4150
    topic_prefix: "local"
    panel_address: 127.0.0.1:4171
  database:
    driver: mysql
    source: root:123456@tcp(192.168.56.162:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.56.162:6379
    dial_timeout: 1s,
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://192.168.56.162:14268/api/traces
